-- Il listino dentro il database: prezzi e ruoli per il negozio della lega
-- aperta (migrazione 019).
--
-- GENERATO da scripts/genera-quotazioni.mjs — non modificare a mano.
-- Rigenerarlo quando cambia il listone (scripts/importa-listone.py), se no il
-- negozio vende ai prezzi dell'anno scorso.
--
-- Si puo' rieseguire: quello che c'e' viene aggiornato, il resto inserito.
-- Chi e' sparito dal listone NON viene cancellato di proposito: e' gia' nella
-- rosa di qualcuno, e cancellarlo lascerebbe rose con giocatori senza prezzo.
--
-- 422 giocatori.

insert into public.quotazioni (player_id, ruolo, quotazione, nome, club) values
  ('academy_1', 'P', 16, 'Giulianelli F.', 'SM Academy U22'),
  ('academy_2', 'P', 16, 'Bucci N.', 'SM Academy U22'),
  ('academy_3', 'P', 15, 'Cenci A.', 'SM Academy U22'),
  ('academy_4', 'P', 12, 'Amici P.', 'SM Academy U22'),
  ('academy_5', 'D', 21, 'Ciacci M.', 'SM Academy U22'),
  ('academy_6', 'D', 18, 'Gasperoni S.', 'SM Academy U22'),
  ('academy_7', 'D', 14, 'Zavoli D.', 'SM Academy U22'),
  ('academy_8', 'D', 12, 'Bullini M.', 'SM Academy U22'),
  ('academy_9', 'D', 12, 'Mirchev N.', 'SM Academy U22'),
  ('academy_10', 'D', 11, 'Delvecchio C.', 'SM Academy U22'),
  ('academy_11', 'D', 11, 'Forcellini S.', 'SM Academy U22'),
  ('academy_12', 'D', 10, 'Grazioso L.', 'SM Academy U22'),
  ('academy_13', 'C', 26, 'Renzi P.', 'SM Academy U22'),
  ('academy_14', 'C', 22, 'Canarezza L.', 'SM Academy U22'),
  ('academy_15', 'C', 22, 'Cervellini T.', 'SM Academy U22'),
  ('academy_16', 'C', 19, 'Molinari G.', 'SM Academy U22'),
  ('academy_17', 'C', 14, 'Grana T.', 'SM Academy U22'),
  ('academy_18', 'C', 13, 'Giorgetti D.', 'SM Academy U22'),
  ('academy_19', 'C', 13, 'Pasolini L.', 'SM Academy U22'),
  ('academy_20', 'C', 12, 'Tamburini M.', 'SM Academy U22'),
  ('academy_21', 'A', 27, 'Valentini F.', 'SM Academy U22'),
  ('academy_22', 'A', 26, 'Famiglietti T.', 'SM Academy U22'),
  ('academy_23', 'A', 23, 'Podeschi T.', 'SM Academy U22'),
  ('cailungo_1', 'P', 18, 'Tordella M.', 'Cailungo'),
  ('cailungo_2', 'P', 10, 'Bannini M.', 'Cailungo'),
  ('cailungo_3', 'P', 9, 'Francioni M.', 'Cailungo'),
  ('cailungo_4', 'D', 20, 'Santi F.', 'Cailungo'),
  ('cailungo_5', 'D', 19, 'Paoli F.', 'Cailungo'),
  ('cailungo_6', 'D', 18, 'Parisi C.', 'Cailungo'),
  ('cailungo_7', 'D', 17, 'Montalti D.', 'Cailungo'),
  ('cailungo_8', 'D', 16, 'Grieco C.', 'Cailungo'),
  ('cailungo_9', 'D', 16, 'Quaranta F.', 'Cailungo'),
  ('cailungo_10', 'D', 13, 'Iuzzolino M.', 'Cailungo'),
  ('cailungo_11', 'D', 13, 'Ir N.', 'Cailungo'),
  ('cailungo_12', 'C', 24, 'Zonzini K.', 'Cailungo'),
  ('cailungo_13', 'C', 22, 'Persichilli L.', 'Cailungo'),
  ('cailungo_14', 'C', 20, 'Colagiovanni M.', 'Cailungo'),
  ('cailungo_15', 'C', 18, 'Tumidei M.', 'Cailungo'),
  ('cailungo_16', 'C', 16, 'Conti A.', 'Cailungo'),
  ('cailungo_17', 'C', 16, 'Boateng S.', 'Cailungo'),
  ('cailungo_18', 'C', 15, 'Tamburrano F.', 'Cailungo'),
  ('cailungo_19', 'C', 14, 'Hirsch Adolfo.', 'Cailungo'),
  ('cailungo_20', 'C', 11, 'Costa E.', 'Cailungo'),
  ('cailungo_21', 'C', 10, 'Casadei M.', 'Cailungo'),
  ('cailungo_22', 'C', 8, 'Bernardi E.', 'Cailungo'),
  ('cailungo_23', 'C', 8, 'Radici T.', 'Cailungo'),
  ('cailungo_24', 'C', 6, 'Senja A.', 'Cailungo'),
  ('cailungo_25', 'A', 37, 'Bua A.', 'Cailungo'),
  ('cailungo_26', 'A', 13, 'Benvenuti L.', 'Cailungo'),
  ('cailungo_27', 'A', 8, 'Cecconi G.', 'Cailungo'),
  ('cosmos_1', 'P', 20, 'Semprini A.', 'Cosmos'),
  ('cosmos_2', 'P', 13, 'Romairone T.', 'Cosmos'),
  ('cosmos_3', 'P', 8, 'Donini L.', 'Cosmos'),
  ('cosmos_4', 'D', 22, 'Bottoni L.', 'Cosmos'),
  ('cosmos_5', 'D', 21, 'Rossi F.', 'Cosmos'),
  ('cosmos_6', 'D', 19, 'Varrella G.', 'Cosmos'),
  ('cosmos_7', 'D', 15, 'Robba G.', 'Cosmos'),
  ('cosmos_8', 'D', 13, 'Palazzi M.', 'Cosmos'),
  ('cosmos_9', 'D', 7, 'Matteoni G.', 'Cosmos'),
  ('cosmos_10', 'D', 6, 'Zaghini F.', 'Cosmos'),
  ('cosmos_11', 'C', 27, 'Sartini N.', 'Cosmos'),
  ('cosmos_12', 'C', 23, 'Braschi L.', 'Cosmos'),
  ('cosmos_13', 'C', 21, 'Lisi D.', 'Cosmos'),
  ('cosmos_14', 'C', 16, 'Tomassini D.', 'Cosmos'),
  ('cosmos_15', 'C', 15, 'Domini T.', 'Cosmos'),
  ('cosmos_16', 'C', 13, 'Rienzo T.', 'Cosmos'),
  ('cosmos_17', 'C', 9, 'D''Addario N.', 'Cosmos'),
  ('cosmos_18', 'C', 8, 'Ulloa R.', 'Cosmos'),
  ('cosmos_19', 'C', 8, 'Tonini V.', 'Cosmos'),
  ('cosmos_20', 'C', 6, 'Grandicelli L.', 'Cosmos'),
  ('cosmos_21', 'A', 33, 'Guidotti R.', 'Cosmos'),
  ('cosmos_22', 'A', 16, 'Rattini A.', 'Cosmos'),
  ('cosmos_23', 'A', 13, 'Cremonini L.', 'Cosmos'),
  ('cosmos_24', 'A', 11, 'Scognamiglio C.', 'Cosmos'),
  ('domagnano_1', 'P', 21, 'Papi F.', 'Domagnano'),
  ('domagnano_2', 'P', 18, 'Bracconi R.', 'Domagnano'),
  ('domagnano_3', 'P', 9, 'Maggioli A.', 'Domagnano'),
  ('domagnano_4', 'P', 7, 'Gregori A.', 'Domagnano'),
  ('domagnano_5', 'D', 23, 'Perazzini D.', 'Domagnano'),
  ('domagnano_6', 'D', 23, 'Guglielmi F.', 'Domagnano'),
  ('domagnano_7', 'D', 22, 'Gozzi E.', 'Domagnano'),
  ('domagnano_8', 'D', 20, 'Rigoni G.', 'Domagnano'),
  ('domagnano_9', 'D', 17, 'Nanni S.', 'Domagnano'),
  ('domagnano_10', 'D', 14, 'Marconi S.', 'Domagnano'),
  ('domagnano_11', 'D', 12, 'Betti L.', 'Domagnano'),
  ('domagnano_12', 'D', 9, 'Valentini F.', 'Domagnano'),
  ('domagnano_13', 'D', 7, 'Valentini G.', 'Domagnano'),
  ('domagnano_14', 'C', 28, 'Fusco M.', 'Domagnano'),
  ('domagnano_15', 'C', 27, 'Contadini L.', 'Domagnano'),
  ('domagnano_16', 'C', 25, 'Buda G.', 'Domagnano'),
  ('domagnano_17', 'C', 23, 'Ferraro N.', 'Domagnano'),
  ('domagnano_18', 'C', 21, 'Michelucci R.', 'Domagnano'),
  ('domagnano_19', 'C', 17, 'Toccaceli A.', 'Domagnano'),
  ('domagnano_20', 'C', 17, 'Gjorretaj S.', 'Domagnano'),
  ('domagnano_21', 'C', 13, 'Bonetti N.', 'Domagnano'),
  ('domagnano_22', 'A', 34, 'Santi S.', 'Domagnano'),
  ('domagnano_23', 'A', 33, 'Babboni D.', 'Domagnano'),
  ('domagnano_24', 'A', 29, 'Arlotti S.', 'Domagnano'),
  ('domagnano_25', 'A', 24, 'Ambrosini A.', 'Domagnano'),
  ('domagnano_26', 'A', 21, 'Menini S.', 'Domagnano'),
  ('domagnano_27', 'A', 8, 'Fortunato L.', 'Domagnano'),
  ('faetano_1', 'P', 19, 'Venturini S.', 'Faetano'),
  ('faetano_2', 'P', 14, 'Panfili T.', 'Faetano'),
  ('faetano_3', 'P', 6, 'Casalboni M.', 'Faetano'),
  ('faetano_4', 'D', 21, 'Tugliani S.', 'Faetano'),
  ('faetano_5', 'D', 21, 'Kokeri S.', 'Faetano'),
  ('faetano_6', 'D', 18, 'Riccardi S.', 'Faetano'),
  ('faetano_7', 'D', 17, 'Bertuccini A.', 'Faetano'),
  ('faetano_8', 'D', 14, 'Palma C.', 'Faetano'),
  ('faetano_9', 'D', 14, 'Abbadessa Cristian.', 'Faetano'),
  ('faetano_10', 'D', 11, 'Salvi S.', 'Faetano'),
  ('faetano_11', 'D', 10, 'Iaccarino G.', 'Faetano'),
  ('faetano_12', 'D', 6, 'Marchese A.', 'Faetano'),
  ('faetano_13', 'D', 6, 'Gentile E.', 'Faetano'),
  ('faetano_14', 'C', 22, 'Elia G.', 'Faetano'),
  ('faetano_15', 'C', 17, 'Renzi A.', 'Faetano'),
  ('faetano_16', 'C', 15, 'Golinucci E.', 'Faetano'),
  ('faetano_17', 'C', 15, 'Bernardi M.', 'Faetano'),
  ('faetano_18', 'C', 13, 'Renzi S.', 'Faetano'),
  ('faetano_19', 'C', 12, 'Cappello S.', 'Faetano'),
  ('faetano_20', 'C', 7, 'Scalcione G.', 'Faetano'),
  ('faetano_21', 'C', 5, 'Ulizio A.', 'Faetano'),
  ('faetano_22', 'C', 5, 'Nicolini F.', 'Faetano'),
  ('faetano_23', 'A', 23, 'Mereu N.', 'Faetano'),
  ('faetano_24', 'A', 16, 'Michelucci D.', 'Faetano'),
  ('faetano_25', 'A', 15, 'Rivas J.', 'Faetano'),
  ('fiorentino_1', 'P', 20, 'Benedettini S.', 'Fiorentino'),
  ('fiorentino_2', 'P', 9, 'Berardi M.', 'Fiorentino'),
  ('fiorentino_3', 'D', 22, 'Cucchi S.', 'Fiorentino'),
  ('fiorentino_4', 'D', 13, 'Costantini M.', 'Fiorentino'),
  ('fiorentino_5', 'D', 9, 'Simiri C.', 'Fiorentino'),
  ('fiorentino_6', 'D', 9, 'Ajmi F.', 'Fiorentino'),
  ('fiorentino_7', 'D', 9, 'Baldon L.', 'Fiorentino'),
  ('fiorentino_8', 'D', 8, 'Ajmi K.', 'Fiorentino'),
  ('fiorentino_9', 'D', 7, 'Frari J.', 'Fiorentino'),
  ('fiorentino_10', 'D', 6, 'Terenzi A.', 'Fiorentino'),
  ('fiorentino_11', 'D', 6, 'Zoffoli F.', 'Fiorentino'),
  ('fiorentino_12', 'C', 26, 'Mariano F.', 'Fiorentino'),
  ('fiorentino_13', 'C', 25, 'Dolcini A.', 'Fiorentino'),
  ('fiorentino_14', 'C', 25, 'Azzurro A.', 'Fiorentino'),
  ('fiorentino_15', 'C', 14, 'Molinari A.', 'Fiorentino'),
  ('fiorentino_16', 'C', 10, 'Grissen N.', 'Fiorentino'),
  ('fiorentino_17', 'C', 7, 'Ledesma F.', 'Fiorentino'),
  ('fiorentino_18', 'C', 7, 'Steger L.', 'Fiorentino'),
  ('fiorentino_19', 'C', 6, 'Passeggio M.', 'Fiorentino'),
  ('fiorentino_20', 'C', 5, 'Borgagni A.', 'Fiorentino'),
  ('fiorentino_21', 'A', 36, 'Pintore M.', 'Fiorentino'),
  ('fiorentino_22', 'A', 17, 'Pesciarelli M.', 'Fiorentino'),
  ('fiorentino_23', 'A', 11, 'Vicente M.', 'Fiorentino'),
  ('folgore_1', 'P', 21, 'Angelis M.', 'Folgore'),
  ('folgore_2', 'P', 18, 'Borasco F.', 'Folgore'),
  ('folgore_3', 'P', 8, 'Russo A.', 'Folgore'),
  ('folgore_4', 'D', 23, 'Battistini M.', 'Folgore'),
  ('folgore_5', 'D', 23, 'Touré Y.', 'Folgore'),
  ('folgore_6', 'D', 21, 'Ramires F.', 'Folgore'),
  ('folgore_7', 'D', 20, 'Fabbri D.', 'Folgore'),
  ('folgore_8', 'D', 19, 'Sartori F.', 'Folgore'),
  ('folgore_9', 'D', 15, 'Brolli C.', 'Folgore'),
  ('folgore_10', 'D', 13, 'Cavalli A.', 'Folgore'),
  ('folgore_11', 'D', 5, 'Marini A.', 'Folgore'),
  ('folgore_12', 'C', 28, 'Pancotti S.', 'Folgore'),
  ('folgore_13', 'C', 26, 'Fall A.', 'Folgore'),
  ('folgore_14', 'C', 25, 'Rufer Az.', 'Folgore'),
  ('folgore_15', 'C', 25, 'Nicolò G.', 'Folgore'),
  ('folgore_16', 'C', 24, 'Raschi J.', 'Folgore'),
  ('folgore_17', 'C', 23, 'Gaiani M.', 'Folgore'),
  ('folgore_18', 'C', 22, 'Malaponti F.', 'Folgore'),
  ('folgore_19', 'C', 20, 'Martins A.', 'Folgore'),
  ('folgore_20', 'C', 9, 'Ankotovych O.', 'Folgore'),
  ('folgore_21', 'C', 7, 'Pierri G.', 'Folgore'),
  ('folgore_22', 'C', 6, 'Sapucci M.', 'Folgore'),
  ('folgore_23', 'A', 39, 'Rufer Au.', 'Folgore'),
  ('folgore_24', 'A', 32, 'Ura R.', 'Folgore'),
  ('folgore_25', 'A', 18, 'Scutella M.', 'Folgore'),
  ('folgore_26', 'A', 9, 'Tampellini E.', 'Folgore'),
  ('juvenes_1', 'P', 21, 'Colonna D.', 'Juvenes/Dogana'),
  ('juvenes_2', 'P', 16, 'Colella R.', 'Juvenes/Dogana'),
  ('juvenes_3', 'P', 11, 'Noto S.', 'Juvenes/Dogana'),
  ('juvenes_4', 'D', 21, 'Pedini F.', 'Juvenes/Dogana'),
  ('juvenes_5', 'D', 20, 'Ghiggini A.', 'Juvenes/Dogana'),
  ('juvenes_6', 'D', 20, 'Sartini S.', 'Juvenes/Dogana'),
  ('juvenes_7', 'D', 19, 'Mazzavillani F.', 'Juvenes/Dogana'),
  ('juvenes_8', 'D', 17, 'Borghini Giac.', 'Juvenes/Dogana'),
  ('juvenes_9', 'D', 16, 'Valle N.', 'Juvenes/Dogana'),
  ('juvenes_10', 'D', 16, 'Calp S.', 'Juvenes/Dogana'),
  ('juvenes_11', 'C', 29, 'Aprea M.', 'Juvenes/Dogana'),
  ('juvenes_12', 'C', 25, 'Lisi K.', 'Juvenes/Dogana'),
  ('juvenes_13', 'C', 20, 'Borghini Gian.', 'Juvenes/Dogana'),
  ('juvenes_14', 'C', 20, 'Lunadei L.', 'Juvenes/Dogana'),
  ('juvenes_15', 'C', 16, 'Merli D.', 'Juvenes/Dogana'),
  ('juvenes_16', 'C', 16, 'Cecchetti L.', 'Juvenes/Dogana'),
  ('juvenes_17', 'C', 15, 'Comuniello A.', 'Juvenes/Dogana'),
  ('juvenes_18', 'C', 15, 'Giovagnoli F.', 'Juvenes/Dogana'),
  ('juvenes_19', 'C', 14, 'Montanari A.', 'Juvenes/Dogana'),
  ('juvenes_20', 'C', 6, 'Addario F.', 'Juvenes/Dogana'),
  ('juvenes_21', 'A', 32, 'Dormi L.', 'Juvenes/Dogana'),
  ('juvenes_22', 'A', 30, 'Amadori N.', 'Juvenes/Dogana'),
  ('juvenes_23', 'A', 25, 'Benedetti G.', 'Juvenes/Dogana'),
  ('lafiorita_1', 'P', 17, 'Vivan G.', 'La Fiorita'),
  ('lafiorita_2', 'P', 17, 'Zavoli M.', 'La Fiorita'),
  ('lafiorita_3', 'P', 12, 'Giuli E.', 'La Fiorita'),
  ('lafiorita_4', 'D', 24, 'Mazzotti M.', 'La Fiorita'),
  ('lafiorita_5', 'D', 23, 'Barretta A.', 'La Fiorita'),
  ('lafiorita_6', 'D', 22, 'Grandoni A.', 'La Fiorita'),
  ('lafiorita_7', 'D', 22, 'Nigretti G.', 'La Fiorita'),
  ('lafiorita_8', 'D', 16, 'Paramatti L.', 'La Fiorita'),
  ('lafiorita_9', 'D', 11, 'Imola N.', 'La Fiorita'),
  ('lafiorita_10', 'C', 30, 'Cicarelli D.', 'La Fiorita'),
  ('lafiorita_11', 'C', 30, 'Semprini J.', 'La Fiorita'),
  ('lafiorita_12', 'C', 29, 'Berardi F.', 'La Fiorita'),
  ('lafiorita_13', 'C', 27, 'Mularoni M.', 'La Fiorita'),
  ('lafiorita_14', 'C', 27, 'Guidi T.', 'La Fiorita'),
  ('lafiorita_15', 'C', 24, 'Enchisi L.', 'La Fiorita'),
  ('lafiorita_16', 'C', 24, 'Zafferani T.', 'La Fiorita'),
  ('lafiorita_17', 'C', 23, 'Errico S.', 'La Fiorita'),
  ('lafiorita_18', 'C', 20, 'Djuric M.', 'La Fiorita'),
  ('lafiorita_19', 'C', 19, 'Vitaioli M.', 'La Fiorita'),
  ('lafiorita_20', 'C', 14, 'Bonifazi T.', 'La Fiorita'),
  ('lafiorita_21', 'C', 8, 'Serges G.', 'La Fiorita'),
  ('lafiorita_22', 'A', 40, 'Bonetti M.', 'La Fiorita'),
  ('lafiorita_23', 'A', 27, 'Nappello U.', 'La Fiorita'),
  ('lafiorita_24', 'A', 20, 'Marcaccini M.', 'La Fiorita'),
  ('libertas_1', 'P', 10, 'Gueye M.', 'Libertas'),
  ('libertas_2', 'P', 7, 'Foiera A.', 'Libertas'),
  ('libertas_3', 'D', 22, 'Vandi P.', 'Libertas'),
  ('libertas_4', 'D', 17, 'Biagi M.', 'Libertas'),
  ('libertas_5', 'D', 16, 'Biagi A.', 'Libertas'),
  ('libertas_6', 'D', 15, 'Gregorio A.', 'Libertas'),
  ('libertas_7', 'D', 15, 'Ginobi K.', 'Libertas'),
  ('libertas_8', 'D', 13, 'Tomassoni L.', 'Libertas'),
  ('libertas_9', 'D', 7, 'Cristiani A.', 'Libertas'),
  ('libertas_10', 'D', 7, 'Magi A.', 'Libertas'),
  ('libertas_11', 'D', 5, 'Lepri M.', 'Libertas'),
  ('libertas_12', 'C', 24, 'Tomassini F.', 'Libertas'),
  ('libertas_13', 'C', 21, 'Socciarelli M.', 'Libertas'),
  ('libertas_14', 'C', 20, 'Greco N.', 'Libertas'),
  ('libertas_15', 'C', 14, 'Morelli G.', 'Libertas'),
  ('libertas_16', 'C', 13, 'Guglielmo L.', 'Libertas'),
  ('libertas_17', 'C', 7, 'Simaha M.', 'Libertas'),
  ('libertas_18', 'C', 6, 'Gori N.', 'Libertas'),
  ('libertas_19', 'A', 19, 'Gabellini A.', 'Libertas'),
  ('libertas_20', 'A', 14, 'Boureima H.', 'Libertas'),
  ('libertas_21', 'A', 12, 'Osayande O.', 'Libertas'),
  ('libertas_22', 'A', 7, 'Melandri D.', 'Libertas'),
  ('murata_1', 'P', 13, 'Suzzi F.', 'Murata'),
  ('murata_2', 'P', 11, 'Olivieri A.', 'Murata'),
  ('murata_3', 'P', 11, 'Magnani M.', 'Murata'),
  ('murata_4', 'D', 12, 'Lombardi L.', 'Murata'),
  ('murata_5', 'D', 12, 'Mozzillo M.', 'Murata'),
  ('murata_6', 'D', 12, 'Kassi O.', 'Murata'),
  ('murata_7', 'D', 10, 'Ceccaroni G.', 'Murata'),
  ('murata_8', 'D', 10, 'Martelli L.', 'Murata'),
  ('murata_9', 'D', 8, 'Raimondi A.', 'Murata'),
  ('murata_10', 'C', 21, 'Baldazzi Alb.', 'Murata'),
  ('murata_11', 'C', 21, 'Palumbo A.', 'Murata'),
  ('murata_12', 'C', 19, 'Peri G.', 'Murata'),
  ('murata_13', 'C', 18, 'Pyantkivskyi I.', 'Murata'),
  ('murata_14', 'C', 17, 'Pasolini F.', 'Murata'),
  ('murata_15', 'C', 17, 'Sarti M.', 'Murata'),
  ('murata_16', 'C', 12, 'Scarcella C.', 'Murata'),
  ('murata_17', 'C', 11, 'Baldani G.', 'Murata'),
  ('murata_18', 'C', 11, 'Hassler L.', 'Murata'),
  ('murata_19', 'C', 10, 'Mauro S.', 'Murata'),
  ('murata_20', 'C', 10, 'Ruocco V.', 'Murata'),
  ('murata_21', 'C', 9, 'Sacchini A.', 'Murata'),
  ('murata_22', 'C', 9, 'Frassanito J.', 'Murata'),
  ('murata_23', 'A', 28, 'Brisigotti A.', 'Murata'),
  ('murata_24', 'A', 22, 'Baldazzi Ale.', 'Murata'),
  ('murata_25', 'A', 19, 'Capodiferro V.', 'Murata'),
  ('murata_26', 'A', 7, 'Capriotti F.', 'Murata'),
  ('pennarossa_1', 'P', 17, 'Manzaroli M.', 'Pennarossa'),
  ('pennarossa_2', 'P', 13, 'Cagnina D.', 'Pennarossa'),
  ('pennarossa_3', 'P', 6, 'Mantia S.', 'Pennarossa'),
  ('pennarossa_4', 'D', 21, 'Evaristi L.', 'Pennarossa'),
  ('pennarossa_5', 'D', 18, 'Arba F.', 'Pennarossa'),
  ('pennarossa_6', 'D', 18, 'Ciacci F.', 'Pennarossa'),
  ('pennarossa_7', 'D', 10, 'Guida G.', 'Pennarossa'),
  ('pennarossa_8', 'D', 8, 'Marconi D.', 'Pennarossa'),
  ('pennarossa_9', 'D', 7, 'Abouzine M.', 'Pennarossa'),
  ('pennarossa_10', 'D', 5, 'Diedhiou H.', 'Pennarossa'),
  ('pennarossa_11', 'C', 29, 'Evaristi M.', 'Pennarossa'),
  ('pennarossa_12', 'C', 28, 'Abouzziane S.', 'Pennarossa'),
  ('pennarossa_13', 'C', 26, 'Belward S.', 'Pennarossa'),
  ('pennarossa_14', 'C', 25, 'Gjonaj A.', 'Pennarossa'),
  ('pennarossa_15', 'C', 21, 'Zahir E.', 'Pennarossa'),
  ('pennarossa_16', 'C', 18, 'Cirillo F.', 'Pennarossa'),
  ('pennarossa_17', 'C', 17, 'Angelini F.', 'Pennarossa'),
  ('pennarossa_18', 'C', 12, 'Zavoli J.', 'Pennarossa'),
  ('pennarossa_19', 'C', 12, 'Boni L.', 'Pennarossa'),
  ('pennarossa_20', 'C', 12, 'Fabbri M.', 'Pennarossa'),
  ('pennarossa_21', 'C', 11, 'Boschi A.', 'Pennarossa'),
  ('pennarossa_22', 'C', 11, 'Chatoyan G.', 'Pennarossa'),
  ('pennarossa_23', 'C', 9, 'Tredicine M.', 'Pennarossa'),
  ('pennarossa_24', 'A', 29, 'Mema M.', 'Pennarossa'),
  ('pennarossa_25', 'A', 22, 'Calderone A.', 'Pennarossa'),
  ('pennarossa_26', 'A', 17, 'Maltoni G.', 'Pennarossa'),
  ('sangiovanni_1', 'P', 19, 'Casadei A.', 'San Giovanni'),
  ('sangiovanni_2', 'P', 14, 'Pizzolante M.', 'San Giovanni'),
  ('sangiovanni_3', 'P', 12, 'Ronci M.', 'San Giovanni'),
  ('sangiovanni_4', 'D', 17, 'Giambalvo A.', 'San Giovanni'),
  ('sangiovanni_5', 'D', 17, 'Vandi F.', 'San Giovanni'),
  ('sangiovanni_6', 'D', 15, 'Fratticci L.', 'San Giovanni'),
  ('sangiovanni_7', 'D', 10, 'Fratta L.', 'San Giovanni'),
  ('sangiovanni_8', 'D', 10, 'Osmani S.', 'San Giovanni'),
  ('sangiovanni_9', 'D', 9, 'Caverzani T.', 'San Giovanni'),
  ('sangiovanni_10', 'D', 8, 'Caddy A.', 'San Giovanni'),
  ('sangiovanni_11', 'D', 8, 'Filippi A.', 'San Giovanni'),
  ('sangiovanni_12', 'D', 8, 'Labudiak V.', 'San Giovanni'),
  ('sangiovanni_13', 'C', 28, 'Zanni M.', 'San Giovanni'),
  ('sangiovanni_14', 'C', 27, 'D''Angeli E.', 'San Giovanni'),
  ('sangiovanni_15', 'C', 26, 'Amati M.', 'San Giovanni'),
  ('sangiovanni_16', 'C', 23, 'Gregori E.', 'San Giovanni'),
  ('sangiovanni_17', 'C', 22, 'Bianchi G.', 'San Giovanni'),
  ('sangiovanni_18', 'C', 18, 'Lisi N.', 'San Giovanni'),
  ('sangiovanni_19', 'C', 12, 'Chiaruzzi N.', 'San Giovanni'),
  ('sangiovanni_20', 'C', 10, 'Rushani I.', 'San Giovanni'),
  ('sangiovanni_21', 'C', 9, 'D''Orsi L.', 'San Giovanni'),
  ('sangiovanni_22', 'C', 7, 'Klyvchuk D.', 'San Giovanni'),
  ('sangiovanni_23', 'A', 30, 'Tumidei F.', 'San Giovanni'),
  ('sangiovanni_24', 'A', 20, 'Spennato M.', 'San Giovanni'),
  ('sangiovanni_25', 'A', 10, 'Scarpellini R.', 'San Giovanni'),
  ('trefiori_1', 'P', 19, 'Nardi M.', 'Tre Fiori'),
  ('trefiori_2', 'P', 15, 'Marchini V.', 'Tre Fiori'),
  ('trefiori_3', 'P', 8, 'Castagnoli A.', 'Tre Fiori'),
  ('trefiori_4', 'D', 24, 'D''Addario A.', 'Tre Fiori'),
  ('trefiori_5', 'D', 24, 'Pesaresi F.', 'Tre Fiori'),
  ('trefiori_6', 'D', 24, 'Sancisi M.', 'Tre Fiori'),
  ('trefiori_7', 'D', 20, 'Mengucci P.', 'Tre Fiori'),
  ('trefiori_8', 'D', 19, 'Sirri A.', 'Tre Fiori'),
  ('trefiori_9', 'D', 19, 'Rea S.', 'Tre Fiori'),
  ('trefiori_10', 'D', 14, 'Guerra A.', 'Tre Fiori'),
  ('trefiori_11', 'D', 14, 'Moretti D.', 'Tre Fiori'),
  ('trefiori_12', 'D', 12, 'Rocchi C.', 'Tre Fiori'),
  ('trefiori_13', 'D', 6, 'Cuzzilla C.', 'Tre Fiori'),
  ('trefiori_14', 'C', 30, 'Sami B.', 'Tre Fiori'),
  ('trefiori_15', 'C', 30, 'Benedettini F.', 'Tre Fiori'),
  ('trefiori_16', 'C', 29, 'Dolcini F.', 'Tre Fiori'),
  ('trefiori_17', 'C', 26, 'Monceri P.', 'Tre Fiori'),
  ('trefiori_18', 'C', 24, 'Censoni L.', 'Tre Fiori'),
  ('trefiori_19', 'C', 19, 'Mandorlini M.', 'Tre Fiori'),
  ('trefiori_20', 'C', 18, 'Terenzi L.', 'Tre Fiori'),
  ('trefiori_21', 'C', 17, 'Sancisi N.', 'Tre Fiori'),
  ('trefiori_22', 'C', 16, 'Ciccione F.', 'Tre Fiori'),
  ('trefiori_23', 'A', 39, 'Bernardi T.', 'Tre Fiori'),
  ('trefiori_24', 'A', 35, 'Prandelli M.', 'Tre Fiori'),
  ('trefiori_25', 'A', 35, 'Kacem M.', 'Tre Fiori'),
  ('trefiori_26', 'A', 14, 'Nek J.', 'Tre Fiori'),
  ('trepenne_1', 'P', 22, 'Migani M.', 'Tre Penne'),
  ('trepenne_2', 'P', 15, 'Benvenuti D.', 'Tre Penne'),
  ('trepenne_3', 'P', 10, 'Andreani F.', 'Tre Penne'),
  ('trepenne_4', 'D', 23, 'Scarcella D.', 'Tre Penne'),
  ('trepenne_5', 'D', 18, 'Ferrani M.', 'Tre Penne'),
  ('trepenne_6', 'D', 14, 'Meriano G.', 'Tre Penne'),
  ('trepenne_7', 'D', 11, 'Kadiu R.', 'Tre Penne'),
  ('trepenne_8', 'D', 7, 'Ruiz B.', 'Tre Penne'),
  ('trepenne_9', 'D', 5, 'Sottile F.', 'Tre Penne'),
  ('trepenne_10', 'C', 29, 'Islamaj K.', 'Tre Penne'),
  ('trepenne_11', 'C', 28, 'Casadio P.', 'Tre Penne'),
  ('trepenne_12', 'C', 28, 'Bartoli T.', 'Tre Penne'),
  ('trepenne_13', 'C', 27, 'Pastorelli L.', 'Tre Penne'),
  ('trepenne_14', 'C', 23, 'Ceccaroli L.', 'Tre Penne'),
  ('trepenne_15', 'C', 20, 'Peluso L.', 'Tre Penne'),
  ('trepenne_16', 'C', 19, 'Loiodice S.', 'Tre Penne'),
  ('trepenne_17', 'C', 18, 'Kamouni M.', 'Tre Penne'),
  ('trepenne_18', 'C', 18, 'Bastianelli T.', 'Tre Penne'),
  ('trepenne_19', 'C', 13, 'Cenni V.', 'Tre Penne'),
  ('trepenne_20', 'C', 11, 'Cenni Mattia.', 'Tre Penne'),
  ('trepenne_21', 'C', 8, 'Cordioli Mario.', 'Tre Penne'),
  ('trepenne_22', 'C', 7, 'Alfano N.', 'Tre Penne'),
  ('trepenne_23', 'C', 5, 'Zafferani G.', 'Tre Penne'),
  ('trepenne_24', 'A', 36, 'Pieri R.', 'Tre Penne'),
  ('trepenne_25', 'A', 24, 'Rinaldi Danilo.', 'Tre Penne'),
  ('trepenne_26', 'A', 10, 'Carrer A.', 'Tre Penne'),
  ('trepenne_27', 'A', 6, 'Mansour A.', 'Tre Penne'),
  ('virtus_1', 'P', 22, 'Venturini G.', 'Virtus'),
  ('virtus_2', 'P', 20, 'Guddo S.', 'Virtus'),
  ('virtus_3', 'P', 7, 'Sebastiani A.', 'Virtus'),
  ('virtus_4', 'D', 22, 'Gori N.', 'Virtus'),
  ('virtus_5', 'D', 19, 'Lucia U.', 'Virtus'),
  ('virtus_6', 'D', 15, 'Piscaglia D.', 'Virtus'),
  ('virtus_7', 'D', 15, 'Nunzella L.', 'Virtus'),
  ('virtus_8', 'D', 11, 'Colombini A.', 'Virtus'),
  ('virtus_9', 'D', 9, 'Madonna D.', 'Virtus'),
  ('virtus_10', 'D', 8, 'Lahrach I.', 'Virtus'),
  ('virtus_11', 'C', 29, 'Ciacci E.', 'Virtus'),
  ('virtus_12', 'C', 28, 'Amati A.', 'Virtus'),
  ('virtus_13', 'C', 27, 'Golinucci A.', 'Virtus'),
  ('virtus_14', 'C', 23, 'Piscitella G.', 'Virtus'),
  ('virtus_15', 'C', 22, 'Buonocunto I.', 'Virtus'),
  ('virtus_16', 'C', 19, 'Yazici A.', 'Virtus'),
  ('virtus_17', 'C', 15, 'Muggeo J.', 'Virtus'),
  ('virtus_18', 'C', 10, 'Blanco B.', 'Virtus'),
  ('virtus_19', 'C', 10, 'Lisanti K.', 'Virtus'),
  ('virtus_20', 'C', 8, 'Borioni N.', 'Virtus'),
  ('virtus_21', 'A', 38, 'Badalassi I.', 'Virtus'),
  ('virtus_22', 'A', 38, 'Benincasa S.', 'Virtus'),
  ('virtus_23', 'A', 31, 'Gjoni A.', 'Virtus'),
  ('virtus_24', 'A', 26, 'Gasperoni M.', 'Virtus'),
  ('cailungo_28', 'C', 5, 'Hirsch Adolfo .', 'Cailungo'),
  ('faetano_26', 'C', 5, 'Abbadessa Cristiano.', 'Faetano'),
  ('trepenne_28', 'C', 5, 'Rinaldi Danilo .', 'Tre Penne'),
  ('academy_24', 'C', 5, 'Montali G.', 'SM Academy U22'),
  ('trepenne_29', 'C', 5, 'Cordioli Mario .', 'Tre Penne'),
  ('trepenne_30', 'C', 5, 'Cenni Mattia .', 'Tre Penne'),
  ('cosmos_25', 'C', 5, 'Brito R.', 'Cosmos'),
  ('sangiovanni_26', 'C', 5, 'Caverzan T.', 'San Giovanni'),
  ('trefiori_27', 'C', 5, 'Nek T.', 'Tre Fiori'),
  ('trefiori_28', 'A', 6, 'Leon B.', 'Tre Fiori'),
  ('sangiovanni_27', 'C', 5, 'Thomas C.', 'San Giovanni'),
  ('lafiorita_25', 'C', 5, 'Daniel C.', 'La Fiorita'),
  ('trepenne_31', 'C', 5, 'Meddi C.', 'Tre Penne'),
  ('cailungo_29', 'P', 6, 'Manuel F.', 'Cailungo'),
  ('academy_25', 'C', 5, 'Giacomo G.', 'SM Academy U22'),
  ('academy_26', 'C', 5, 'Nicola M.', 'SM Academy U22'),
  ('academy_27', 'D', 5, 'Gabriele M.', 'SM Academy U22'),
  ('academy_28', 'C', 5, 'Alessandro M.', 'SM Academy U22'),
  ('libertas_23', 'A', 6, 'Osagie O.', 'Libertas'),
  ('cailungo_30', 'D', 5, 'Ciro P.', 'Cailungo'),
  ('virtus_25', 'A', 6, 'Gianmario P.', 'Virtus'),
  ('murata_27', 'C', 5, 'Andrea R.', 'Murata'),
  ('trepenne_32', 'C', 5, 'Ezequiel R.', 'Tre Penne'),
  ('cosmos_26', 'C', 5, 'Richard U.', 'Cosmos')
on conflict (player_id) do update
  set ruolo = excluded.ruolo, quotazione = excluded.quotazione,
      nome = excluded.nome, club = excluded.club;
