export { dashboard } from './dashboard.js';
export { rosa } from './rosa.js';
export { formazione } from './formazione.js';
export { calendario } from './calendario.js';
export { classifica } from './classifica.js';
export { voti } from './voti.js';
export { live } from './live.js';
export { video } from './video.js';
export { listone } from './listone.js';
export { giocatore } from './giocatore.js';
export { regolamento } from './regolamento.js';
export { regole } from './regole.js';
export { scheda } from './scheda.js';
export { impostazioni, avanzate } from './impostazioni.js';
export { scambi } from './scambi.js';
export { confronto } from './confronto.js';
export { privacy, termini, archiviazione, licenze } from './legali.js';
export { mercato } from './mercato.js';
export { asta } from './asta.js';
export { adminGiornata, adminPartita, adminContestazioni, adminCongela, adminRegistro, adminConsole } from './admin.js';
export { login, resetLogin, prepareLogin } from './auth.js';
export { onboarding } from './onboarding.js';
export { setup, offline } from './setup.js';
export { sospeso } from './sospeso.js';
export { leghe } from './leghe.js';
export { lega } from './lega.js';
export { gestione } from './gestione.js';
export { squadra } from './squadra.js';
export { vice } from './vice.js';
