import * as S from '../state.js';
import { fmt } from '../ui.js';

export const regolamento = {
  title: 'Regolamento', appbar: 'back', sub: () => 'Regolamento ed opzioni',
  render() {
    const r = S.rules(); const row = (k, v) => `<tr><td>${k}</td><td class="num" style="text-align:right">${v}</td></tr>`;
    return `<main class="a-body rules">
      <div class="a-card"><p class="rule-art">PRINCIPIO FONDANTE</p><p>Non esistendo pagelle per il Campionato Sammarinese, nessun voto è espresso da una redazione. Ogni valutazione nasce da eventi oggettivi e verificabili del referto FSGC, eventualmente confermati dal video di Titani.TV. Il referto fa fede; nessun giudizio soggettivo; il dato si congela.</p></div>
      <h3>Art. 4 — Voto base (Voto Titano)</h3>
      <table><tr><th>Condizione</th><th>Voto</th></tr>${row('Almeno 20 minuti', fmt(r.baseVote))}${row('Meno di 20 minuti senza eventi', 'S.V.')}${row('Meno di 20 minuti con eventi', fmt(r.baseVote) + ' + eventi')}${row('Non entrato / squalificato', 'S.V.')}</table>
      <table><tr><th>Esito collettivo</th><th>≥ 60\'</th><th>20–59\'</th></tr><tr><td>Vittoria</td><td class="num">+${fmt(r.outcome.win)}</td><td class="num">+${fmt(r.outcome.win * r.partialWeight, 2)}</td></tr><tr><td>Pareggio</td><td class="num">0</td><td class="num">0</td></tr><tr><td>Sconfitta</td><td class="num">−${fmt(-r.outcome.loss)}</td><td class="num">−${fmt(-r.outcome.loss * r.partialWeight, 2)}</td></tr></table>
      <h3>Art. 5 — Bonus e malus</h3>
      <table><tr><th>Gol per ruolo</th><th></th></tr>${row('Portiere', '+' + fmt(r.goal.P))}${row('Difensore', '+' + fmt(r.goal.D))}${row('Centrocampista', '+' + fmt(r.goal.C))}${row('Attaccante', '+' + fmt(r.goal.A))}</table>
      <table><tr><th>Evento</th><th></th></tr>${row('Assist', '+' + fmt(r.assist))}${row('Assist da palla inattiva', r.assistSetPiece ? '+' + fmt(r.assistSetPiece) : 'come gli altri')}${row('Gol decisivo (pari o sorpasso)', r.decisiveGoal ? '+' + fmt(r.decisiveGoal) : 'spento')}${row('Porta inviolata portiere (min. 60\')', '+' + fmt(r.cleanSheet.P))}${row('Porta inviolata difensore (min. 60\')', '+' + fmt(r.cleanSheet.D))}${row('Gol subito — portiere', fmt(r.goalConcededGK))}${row('Rigore parato', '+' + fmt(r.penSaved))}${row('Rigore sbagliato', fmt(r.penMissed))}${row('Autogol', fmt(r.ownGoal))}${row('Ammonizione', fmt(r.yellow))}${row('Espulsione per doppia ammonizione', fmt(r.secondYellow) + ' (cumulabile: −1,5)')}${row('Espulsione per rosso diretto', fmt(r.redDirect))}${row('Rigore procurato / causato (livello 2)', r.level2Events ? '+1,0 / −1,0' : 'disattivati')}</table>
      <h3>Art. 6 — Capitano</h3><p>Raddoppia bonus e malus, non il voto base. Se è S.V. subentra il vice; se anche il vice è S.V., nessun raddoppio.</p>
      <h3>Art. 7 — Definizioni</h3><p>Minuti da referto, recupero escluso. Assist: ultimo passaggio volontario verso la conclusione vincente, uno per gol, nel dubbio nessuno. Autogol: −2,0 e gol subito per il proprio portiere. Rigore segnato = gol normale. Porta inviolata: conta il risultato finale, min. 60'. Cambio portiere: il malus va a chi è in campo al momento del gol. Movimento in porta: mantiene il ruolo da listone.</p>
      <h3>Art. 7-bis — A chi va il gol, l'autogol, l'assist</h3>
      <p><b>Gol deviato.</b> Se il tiro era diretto in porta e un avversario lo devia per reazione istintiva, il gol resta a chi ha tirato: non è autogol. È autogol solo quando la deviazione riguarda un pallone che <i>non</i> era indirizzato nello specchio.</p>
      <p><b>Deviazione di un compagno.</b> Tiro verso la porta deviato involontariamente da un compagno: gol a chi ha tirato. Se invece il compagno interviene attivamente e cambia in modo netto la traiettoria, il gol è suo.</p>
      <p><b>Nel dubbio</b> sulla destinazione del tiro, il gol va a chi ha tirato.</p>
      <p><b>Assist.</b> Va assegnato solo se il passaggio è volontario, cioè se è ragionevole ritenere che cercasse un compagno: un tiro in porta che un compagno devia dentro non è un assist. Se un difensore tocca senza alterare la traiettoria l'assist resta; se la altera in modo significativo decade. Uno solo per gol; nel dubbio nessuno.</p>
      <p class="rule-art">CRITERI RIPRESI DAL REGOLAMENTO FANTACALCIO GOL/AUTOGOL E ASSIST, ADATTATI AL REFERTO FSGC. IL GIUDICE DATI DECIDE E REGISTRA IL PRECEDENTE (ART. 9).</p>
      <h3>Art. 8 — Formazioni</h3><p>11 titolari + 7 panchinari ordinati. Moduli: ${r.modules.join(', ')}. Lock all'inizio della prima gara. Non consegnata: ultima formazione valida; alla prima giornata 4-4-2 con le quotazioni più alte. Sostituzioni automatiche: ordine di panchina, massimo ${r.maxSubs}; senza sostituto il titolare vale ${fmt(r.noSubVote)}. Entra il primo panchinaro dello stesso ruolo${r.subMode === 'free' ? '; se nel ruolo non c\'è nessuno con voto entra comunque il primo disponibile e il modulo cambia (modulo libero)' : '. Il modulo non cambia: se nel ruolo non c\'è nessuno, nessuna sostituzione'}.</p>
      <h3>Art. 9 — Tempi</h3><p>Punteggi provvisori entro domenica 23:59. Contestazioni entro martedì 18:00, per iscritto, con evento e minuto. Congelamento martedì 20:00: la giornata non è più rettificabile. Il Giudice Dati decide sui casi non previsti e registra i precedenti.</p>
      <h3>Art. 10 — Gare anomale</h3><p>Rinviata: S.V. (se recuperata entro il martedì, voti validi). Sospesa prima del 45': S.V. per tutti. Sospesa dopo: eventi validi, niente porta inviolata né esito collettivo. A tavolino: S.V. per tutti i 22. Omologata con punteggio modificato: esito e porta inviolata sul risultato omologato, eventi reali validi.</p>
      <h3>Art. 11 — Conversione in gol</h3>
      <table><tr><th>Fantallenatori</th><th>Soglia</th><th>Passo</th></tr>${r.conversion.map((c) => `<tr><td>${c.min}–${c.max}</td><td class="num">${fmt(c.threshold)}</td><td class="num">${fmt(c.step)}</td></tr>`).join('')}</table><p>Parità di fantapunteggio = pareggio.${r.homeBonus ? ` Fattore campo: chi gioca in casa somma <b>+${fmt(r.homeBonus)}</b> al proprio fantapunteggio.` : ' Nessun fattore campo.'}</p>
      <h3>Art. 12 — Classifica</h3><p>3 punti a vittoria, 1 a pareggio. Spareggi: punti › fantapunti stagionali › differenza reti › scontri diretti.</p>
      <h3>Art. 13 — Regole del fantacalcio che qui non si applicano</h3>
      <p><b>Modificatore di difesa.</b> Nel fantacalcio classico si fa la media dei <i>voti</i> di portiere e tre migliori difensori e si trasforma in bonus. Qui non può funzionare: il Voto Titano non è una pagella, il voto base è 6,0 uguale per tutti quelli che giocano almeno 20 minuti, più o meno mezzo punto di esito collettivo identico per tutti i compagni. La media sarebbe la stessa per chiunque schieri una difesa intera e il modificatore darebbe a tutti lo stesso numero. Non è una scelta di gusto: la regola non ha su cosa lavorare.</p>
      <p><b>Quality assist (soft, standard, gold).</b> Distinguere l'assist per quanto era difficile la giocata è un giudizio, e i giudizi qui non entrano (art. 1). Resta la sola distinzione che il referto sa dare da sé: palla inattiva o azione.</p>
      <p><b>Sistema Mantra.</b> Richiede i ruoli dettagliati (Pc, Tc, W, ...) che il listone FSGC non ha.</p>
      <h3>Opzioni di lega</h3>
      <a class="a-btn sec" href="#/regole" style="text-decoration:none;margin-bottom:8px">Cambia le opzioni di regolamento</a>
      <table>${row('Budget', r.budget)}${row('Rosa', `${r.roster.P}P · ${r.roster.D}D · ${r.roster.C}C · ${r.roster.A}A`)}${row('Tetto per società', r.maxPerClub || 'nessuno')}${row('Eventi livello 2', r.level2Events ? 'attivi' : 'spenti')}${row('Sostituzioni', r.subMode === 'free' ? 'modulo libero' : 'stesso ruolo')}${row('Cambi massimi', r.maxSubs)}${row('Fattore campo', r.homeBonus ? '+' + fmt(r.homeBonus) : 'spento')}${row('Gol decisivo', r.decisiveGoal ? '+' + fmt(r.decisiveGoal) : 'spento')}${row('Assist da fermo', r.assistSetPiece ? '+' + fmt(r.assistSetPiece) : 'come gli altri')}${row('Motore', r.engineVersion)}</table>
    </main>`;
  },
};
