/**
 * Listone reale del Campionato Sammarinese.
 *
 * GENERATO da scripts/importa-listone.py — non modificare a mano.
 * Fonte: Transfermarkt. Rilanciare lo script quando le rose cambiano.
 *
 * Forma compatta per non gonfiare il file: [clubId, nome, cognome, ruolo, quotazione, eta]
 */
export const LISTONE = [
  ["academy","Filippo","Giulianelli","P",16,18],
  ["academy","Nicholas","Bucci","P",16,16],
  ["academy","Alessandro","Cenci","P",15,18],
  ["academy","Pietro","Amici","P",12,22],
  ["academy","Mattia","Ciacci","D",21,20],
  ["academy","Simone","Gasperoni","D",18,20],
  ["academy","Diego","Zavoli","D",14,22],
  ["academy","Mattia","Bullini","D",12,18],
  ["academy","Nikolai Yordan","Mirchev","D",12,18],
  ["academy","Christian","Delvecchio","D",11,18],
  ["academy","Samuele","Forcellini","D",11,19],
  ["academy","Lorenzo","Grazioso","D",10,20],
  ["academy","Pietro","Renzi","C",26,21],
  ["academy","Lorenzo","Canarezza","C",22,18],
  ["academy","Tommy","Cervellini","C",22,20],
  ["academy","Giacomo","Molinari","C",19,21],
  ["academy","Thomas","Grana","C",14,17],
  ["academy","Denis","Giorgetti","C",13,18],
  ["academy","Luca","Pasolini","C",13,18],
  ["academy","Mattia","Tamburini","C",12,19],
  ["academy","Filippo","Valentini","A",27,19],
  ["academy","Tommaso","Famiglietti","A",26,21],
  ["academy","Tommaso","Podeschi","A",23,18],
  ["cailungo","Manuel","Tordella","P",18,28],
  ["cailungo","Mirco","Bannini","P",10,30],
  ["cailungo","Massimo","Francioni","P",9,33],
  ["cailungo","Filippo","Santi","D",20,25],
  ["cailungo","Federico De","Paoli","D",19,27],
  ["cailungo","Ciro","Parisi","D",18,21],
  ["cailungo","Davide","Montalti","D",17,22],
  ["cailungo","Cristian","Grieco","D",16,27],
  ["cailungo","Filippo","Quaranta","D",16,28],
  ["cailungo","Manuel","Iuzzolino","D",13,36],
  ["cailungo","Nasr Eddine","Ir","D",13,30],
  ["cailungo","Kevin","Zonzini","C",24,29],
  ["cailungo","Lorenzo","Persichilli","C",22,22],
  ["cailungo","Matias","Colagiovanni","C",20,33],
  ["cailungo","Matteo","Tumidei","C",18,22],
  ["cailungo","Alessandro","Conti","C",16,28],
  ["cailungo","Samuel Adu","Boateng","C",16,27],
  ["cailungo","Francesco","Tamburrano","C",15,29],
  ["cailungo","Adolfo","Hirsch","C",14,40],
  ["cailungo","Emanuele","Costa","C",11,20],
  ["cailungo","Matteo Valli","Casadei","C",10,21],
  ["cailungo","Edoardo","Bernardi","C",8,23],
  ["cailungo","Thomas","Radici","C",8,24],
  ["cailungo","Armando","Senja","C",6,29],
  ["cailungo","Antonio","Bua","A",37,25],
  ["cailungo","Lorenzo","Benvenuti","A",13,24],
  ["cailungo","Giacomo","Cecconi","A",8,31],
  ["cosmos","Alessandro","Semprini","P",20,32],
  ["cosmos","Teo","Romairone","P",13,20],
  ["cosmos","Luca","Donini","P",8,37],
  ["cosmos","Luca","Bottoni","D",22,30],
  ["cosmos","Francesco","Rossi","D",21,21],
  ["cosmos","Gabriele","Varrella","D",19,31],
  ["cosmos","Gast\u00f3n Rodrigo","Robba","D",15,32],
  ["cosmos","Mirko","Palazzi","D",13,39],
  ["cosmos","Giacomo","Matteoni","D",7,24],
  ["cosmos","Francesco","Zaghini","D",6,26],
  ["cosmos","Nicola","Sartini","C",27,27],
  ["cosmos","Lorenzo","Braschi","C",23,32],
  ["cosmos","Davide","Lisi","C",21,25],
  ["cosmos","David","Tomassini","C",16,26],
  ["cosmos","Tommaso","Domini","C",15,37],
  ["cosmos","Tommaso Di","Rienzo","C",13,18],
  ["cosmos","Nicola","D'Addario","C",9,22],
  ["cosmos","Richard","Ulloa","C",8,24],
  ["cosmos","Vittorio","Tonini","C",8,24],
  ["cosmos","Luca","Grandicelli","C",6,28],
  ["cosmos","Roberto","Guidotti","A",33,23],
  ["cosmos","Alessandro","Rattini","A",16,20],
  ["cosmos","Leon","Cremonini","A",13,23],
  ["cosmos","Carlo","Scognamiglio","A",11,25],
  ["domagnano","Filippo","Papi","P",21,23],
  ["domagnano","Raffaele","Bracconi","P",18,23],
  ["domagnano","Alessandro","Maggioli","P",9,33],
  ["domagnano","Andrea","Gregori","P",7,38],
  ["domagnano","Diego","Perazzini","D",23,26],
  ["domagnano","Filippo","Guglielmi","D",23,25],
  ["domagnano","Enrico","Gozzi","D",22,28],
  ["domagnano","Giammaria","Rigoni","D",20,27],
  ["domagnano","Simone","Nanni","D",17,26],
  ["domagnano","Samuele","Marconi","D",14,22],
  ["domagnano","Leone","Betti","D",12,18],
  ["domagnano","Filippo","Valentini","D",9,20],
  ["domagnano","Giacomo","Valentini","D",7,25],
  ["domagnano","Mattia","Fusco","C",28,21],
  ["domagnano","Lorenzo","Contadini","C",27,31],
  ["domagnano","Giacomo","Buda","C",25,26],
  ["domagnano","Nicolas","Ferraro","C",23,31],
  ["domagnano","Riccardo","Michelucci","C",21,23],
  ["domagnano","Alex","Toccaceli","C",17,24],
  ["domagnano","Samel","Gjorretaj","C",17,24],
  ["domagnano","Nicola","Bonetti","C",13,18],
  ["domagnano","Simone","Santi","A",34,22],
  ["domagnano","Daniele","Babboni","A",33,26],
  ["domagnano","Scott","Arlotti","A",29,27],
  ["domagnano","Alex","Ambrosini","A",24,39],
  ["domagnano","Simone","Menini","A",21,19],
  ["domagnano","Lorenzo","Fortunato","A",8,27],
  ["faetano","Simone","Venturini","P",19,28],
  ["faetano","Tommaso","Panfili","P",14,19],
  ["faetano","Marco","Casalboni","P",6,43],
  ["faetano","Samuele","Tugliani","D",21,22],
  ["faetano","Stefano","Kokeri","D",21,20],
  ["faetano","Simone","Riccardi","D",18,20],
  ["faetano","Alessio","Bertuccini","D",17,21],
  ["faetano","Ciro Di","Palma","D",14,19],
  ["faetano","Cristian","Abbadessa","D",14,19],
  ["faetano","Simone","Salvi","D",11,19],
  ["faetano","Giovanni","Iaccarino","D",10,19],
  ["faetano","Antonio","Marchese","D",6,30],
  ["faetano","Ernesto","Gentile","D",6,27],
  ["faetano","Giuseppe","Elia","C",22,21],
  ["faetano","Alessandro","Renzi","C",17,23],
  ["faetano","Enrico","Golinucci","C",15,35],
  ["faetano","Marco","Bernardi","C",15,32],
  ["faetano","Samuele","Renzi","C",13,19],
  ["faetano","Salvatore","Cappello","C",12,19],
  ["faetano","Gian Luca","Scalcione","C",7,26],
  ["faetano","Andrea","Ulizio","C",5,32],
  ["faetano","Federico","Nicolini","C",5,null],
  ["faetano","Nicol\u00f2","Mereu","A",23,16],
  ["faetano","Diego","Michelucci","A",16,21],
  ["faetano","Juan David","Rivas","A",15,22],
  ["fiorentino","Simone","Benedettini","P",20,29],
  ["fiorentino","Michele","Berardi","P",9,34],
  ["fiorentino","Stefano","Cucchi","D",22,29],
  ["fiorentino","Mattia","Costantini","D",13,37],
  ["fiorentino","Cristian","Simiri","D",9,20],
  ["fiorentino","Fedi","Ajmi","D",9,20],
  ["fiorentino","Luca","Baldon","D",9,21],
  ["fiorentino","Khalifa","Ajmi","D",8,22],
  ["fiorentino","Joaquin Del","Frari","D",7,25],
  ["fiorentino","Alessandro","Terenzi","D",6,26],
  ["fiorentino","Filippo","Zoffoli","D",6,29],
  ["fiorentino","Francesco","Mariano","C",26,21],
  ["fiorentino","Andrea","Dolcini","C",25,23],
  ["fiorentino","Antonio","Azzurro","C",25,27],
  ["fiorentino","Alessandro","Molinari","C",14,37],
  ["fiorentino","Nour","Grissen","C",10,21],
  ["fiorentino","Francisco Jes\u00fas","Ledesma","C",7,24],
  ["fiorentino","Luciano","Steger","C",7,24],
  ["fiorentino","Matteo","Passeggio","C",6,28],
  ["fiorentino","Andrea","Borgagni","C",5,32],
  ["fiorentino","Mattia","Pintore","A",36,27],
  ["fiorentino","Manuel","Pesciarelli","A",17,20],
  ["fiorentino","Mario Jos\u00e9","Vicente","A",11,25],
  ["folgore","Mirco De","Angelis","P",21,26],
  ["folgore","Fabio","Borasco","P",18,20],
  ["folgore","Angelo","Russo","P",8,38],
  ["folgore","Manuel","Battistini","D",23,32],
  ["folgore","Yero","Tour\u00e9","D",23,24],
  ["folgore","Francesco","Ramires","D",21,22],
  ["folgore","Diego","Fabbri","D",20,22],
  ["folgore","Francesco","Sartori","D",19,33],
  ["folgore","Cristian","Brolli","D",15,34],
  ["folgore","Alex","Cavalli","D",13,34],
  ["folgore","Alex","Marini","D",5,43],
  ["folgore","Samuel","Pancotti","C",28,25],
  ["folgore","Assane","Fall","C",26,32],
  ["folgore","Azael Garcia","Rufer","C",25,23],
  ["folgore","Giovanni De","Nicol\u00f2","C",25,22],
  ["folgore","Jacopo","Raschi","C",24,28],
  ["folgore","Matteo","Gaiani","C",23,31],
  ["folgore","Federico","Malaponti","C",22,19],
  ["folgore","Adam Adami","Martins","C",20,34],
  ["folgore","Oleg","Ankotovych","C",9,22],
  ["folgore","Giuseppe","Pierri","C",7,26],
  ["folgore","Matteo","Sapucci","C",6,28],
  ["folgore","Augusto Garcia","Rufer","A",39,27],
  ["folgore","Raul","Ura","A",32,28],
  ["folgore","Matias","Scutella","A",18,20],
  ["folgore","Eros","Tampellini","A",9,26],
  ["juvenes","Davide","Colonna","P",21,25],
  ["juvenes","Rocco","Colella","P",16,18],
  ["juvenes","Simone Di","Noto","P",11,30],
  ["juvenes","Filippo","Pedini","D",21,22],
  ["juvenes","Andrea","Ghiggini","D",20,26],
  ["juvenes","Stefano","Sartini","D",20,26],
  ["juvenes","Francesco","Mazzavillani","D",19,28],
  ["juvenes","Giacomo","Borghini","D",17,25],
  ["juvenes","Nicola Della","Valle","D",16,29],
  ["juvenes","Santiago Tomas","Calp","D",16,26],
  ["juvenes","Mattia","Aprea","C",29,22],
  ["juvenes","Kevin","Lisi","C",25,24],
  ["juvenes","Gianmaria","Borghini","C",20,29],
  ["juvenes","Lorenzo","Lunadei","C",20,29],
  ["juvenes","Davide","Merli","C",16,26],
  ["juvenes","Luca","Cecchetti","C",16,26],
  ["juvenes","Andrea","Comuniello","C",15,31],
  ["juvenes","Fabio","Giovagnoli","C",15,34],
  ["juvenes","Andrea","Montanari","C",14,39],
  ["juvenes","Federico Di","Addario","C",6,28],
  ["juvenes","Lorenzo","Dormi","A",32,31],
  ["juvenes","Nicol\u00f2","Amadori","A",30,21],
  ["juvenes","Gianluca","Benedetti","A",25,30],
  ["lafiorita","Gianluca","Vivan","P",17,42],
  ["lafiorita","Matteo","Zavoli","P",17,30],
  ["lafiorita","Elia Di","Giuli","P",12,22],
  ["lafiorita","Marco","Mazzotti","D",24,28],
  ["lafiorita","Antonio","Barretta","D",23,30],
  ["lafiorita","Andrea","Grandoni","D",22,29],
  ["lafiorita","Giacomo","Nigretti","D",22,27],
  ["lafiorita","Lorenzo","Paramatti","D",16,31],
  ["lafiorita","Nicol\u00f2","Imola","D",11,19],
  ["lafiorita","Daniel","Cicarelli","C",30,28],
  ["lafiorita","Jacopo","Semprini","C",30,24],
  ["lafiorita","Filippo","Berardi","C",29,29],
  ["lafiorita","Marcello","Mularoni","C",27,28],
  ["lafiorita","Tommaso","Guidi","C",27,28],
  ["lafiorita","Lorenzo","Enchisi","C",24,29],
  ["lafiorita","Tommaso","Zafferani","C",24,30],
  ["lafiorita","Simone","Errico","C",23,34],
  ["lafiorita","Marco","Djuric","C",20,33],
  ["lafiorita","Matteo","Vitaioli","C",19,36],
  ["lafiorita","Thomas","Bonifazi","C",14,16],
  ["lafiorita","Giuseppe","Serges","C",8,23],
  ["lafiorita","Matthias","Bonetti","A",40,24],
  ["lafiorita","Umberto","Nappello","A",27,35],
  ["lafiorita","Mattia","Marcaccini","A",20,19],
  ["libertas","Moussa","Gueye","P",10,30],
  ["libertas","Alex","Foiera","P",7,41],
  ["libertas","Paolo","Vandi","D",22,31],
  ["libertas","Manuel De","Biagi","D",17,24],
  ["libertas","Alex De","Biagi","D",16,26],
  ["libertas","Angelo","Gregorio","D",15,35],
  ["libertas","Kristian","Ginobi","D",15,19],
  ["libertas","Luca","Tomassoni","D",13,31],
  ["libertas","Andrea","Cristiani","D",7,25],
  ["libertas","Andrea","Magi","D",7,25],
  ["libertas","Matteo","Lepri","D",5,37],
  ["libertas","Fabio Ramon","Tomassini","C",24,30],
  ["libertas","Manuel","Socciarelli","C",21,24],
  ["libertas","Nicola","Greco","C",20,26],
  ["libertas","Gian Luca","Morelli","C",14,41],
  ["libertas","Luca","Guglielmo","C",13,18],
  ["libertas","Moussa","Simaha","C",7,27],
  ["libertas","Nicola","Gori","C",6,29],
  ["libertas","Alessandro","Gabellini","A",19,19],
  ["libertas","Hamza Hamidou","Boureima","A",14,22],
  ["libertas","Osagie","Osayande","A",12,25],
  ["libertas","Daniele","Melandri","A",7,37],
  ["murata","Francesco","Suzzi","P",13,19],
  ["murata","Alberto","Olivieri","P",11,24],
  ["murata","Michele","Magnani","P",11,23],
  ["murata","Leonardo","Lombardi","D",12,17],
  ["murata","Manuel","Mozzillo","D",12,18],
  ["murata","Omar","Kassi","D",12,18],
  ["murata","Giacomo","Ceccaroni","D",10,19],
  ["murata","Luca","Martelli","D",10,20],
  ["murata","Alessandro","Raimondi","D",8,21],
  ["murata","Alberto","Baldazzi","C",21,24],
  ["murata","Antonio","Palumbo","C",21,23],
  ["murata","Giacomo","Peri","C",19,20],
  ["murata","Ivan","Pyantkivskyi","C",18,22],
  ["murata","Filippo","Pasolini","C",17,23],
  ["murata","Mattia","Sarti","C",17,23],
  ["murata","Cristian","Scarcella","C",12,19],
  ["murata","Gianluca","Baldani","C",11,20],
  ["murata","Luca","Hassler","C",11,20],
  ["murata","Salvatore Di","Mauro","C",10,21],
  ["murata","Vincenzo","Ruocco","C",10,22],
  ["murata","Alessandro","Sacchini","C",9,22],
  ["murata","Joshua","Frassanito","C",9,22],
  ["murata","Alessandro","Brisigotti","A",28,32],
  ["murata","Alessandro","Baldazzi","A",22,18],
  ["murata","Vito","Capodiferro","A",19,20],
  ["murata","Filippo","Capriotti","A",7,33],
  ["pennarossa","Mattia","Manzaroli","P",17,34],
  ["pennarossa","Daniele","Cagnina","P",13,21],
  ["pennarossa","Simone La","Mantia","P",6,47],
  ["pennarossa","Luca","Evaristi","D",21,20],
  ["pennarossa","Federico","Arba","D",18,21],
  ["pennarossa","Federico","Ciacci","D",18,21],
  ["pennarossa","Giuliano","Guida","D",10,20],
  ["pennarossa","Davide","Marconi","D",8,21],
  ["pennarossa","Mouhcine","Abouzine","D",7,26],
  ["pennarossa","Herv\u00e9","Diedhiou","D",5,32],
  ["pennarossa","Marco","Evaristi","C",29,26],
  ["pennarossa","Sami","Abouzziane","C",28,24],
  ["pennarossa","Soufiane","Belward","C",26,22],
  ["pennarossa","Alen","Gjonaj","C",25,22],
  ["pennarossa","Eleas","Zahir","C",21,25],
  ["pennarossa","Federico","Cirillo","C",18,21],
  ["pennarossa","Francesco","Angelini","C",17,23],
  ["pennarossa","Jacopo","Zavoli","C",12,19],
  ["pennarossa","Luca De","Boni","C",12,19],
  ["pennarossa","Mattia","Fabbri","C",12,20],
  ["pennarossa","Alessio","Boschi","C",11,20],
  ["pennarossa","Gor","Chatoyan","C",11,20],
  ["pennarossa","Manuel","Tredicine","C",9,22],
  ["pennarossa","Marseljan","Mema","A",29,29],
  ["pennarossa","Armando","Calderone","A",22,18],
  ["pennarossa","Gianmarco","Maltoni","A",17,20],
  ["sangiovanni","Alessandro","Casadei","P",19,21],
  ["sangiovanni","Manuel","Pizzolante","P",14,19],
  ["sangiovanni","Matteo","Ronci","P",12,22],
  ["sangiovanni","Alessandro","Giambalvo","D",17,23],
  ["sangiovanni","Federico","Vandi","D",17,22],
  ["sangiovanni","Luca","Fratticci","D",15,19],
  ["sangiovanni","Leonardo","Fratta","D",10,20],
  ["sangiovanni","Simone","Osmani","D",10,20],
  ["sangiovanni","Thomas","Caverzani","D",9,21],
  ["sangiovanni","Alex","Caddy","D",8,21],
  ["sangiovanni","Andrea Carlos","Filippi","D",8,21],
  ["sangiovanni","Valerii","Labudiak","D",8,22],
  ["sangiovanni","Mattia","Zanni","C",28,22],
  ["sangiovanni","Eric","D'Angeli","C",27,26],
  ["sangiovanni","Mattia","Amati","C",26,20],
  ["sangiovanni","Emanuele","Gregori","C",23,31],
  ["sangiovanni","Gianluca","Bianchi","C",22,19],
  ["sangiovanni","Nicholas","Lisi","C",18,22],
  ["sangiovanni","Nicol\u00f2","Chiaruzzi","C",12,20],
  ["sangiovanni","Ilvi","Rushani","C",10,21],
  ["sangiovanni","Lorenzo","D'Orsi","C",9,22],
  ["sangiovanni","Denys","Klyvchuk","C",7,27],
  ["sangiovanni","Federico","Tumidei","A",30,24],
  ["sangiovanni","Marco","Spennato","A",20,19],
  ["sangiovanni","Ryan","Scarpellini","A",10,26],
  ["trefiori","Michele","Nardi","P",19,40],
  ["trefiori","Vittorio","Marchini","P",15,19],
  ["trefiori","Alex","Castagnoli","P",8,37],
  ["trefiori","Alessandro","D'Addario","D",24,29],
  ["trefiori","Federico","Pesaresi","D",24,30],
  ["trefiori","Mattia","Sancisi","D",24,23],
  ["trefiori","Pietro","Mengucci","D",20,23],
  ["trefiori","Alex","Sirri","D",19,35],
  ["trefiori","Simone","Rea","D",19,33],
  ["trefiori","Alberto","Guerra","D",14,22],
  ["trefiori","Diego","Moretti","D",14,26],
  ["trefiori","Cristian","Rocchi","D",12,18],
  ["trefiori","Claudio","Cuzzilla","D",6,28],
  ["trefiori","Brando","Sami","C",30,25],
  ["trefiori","Federico","Benedettini","C",30,23],
  ["trefiori","Federico","Dolcini","C",29,26],
  ["trefiori","Pavel","Monceri","C",26,20],
  ["trefiori","Luca","Censoni","C",24,30],
  ["trefiori","Matteo","Mandorlini","C",19,37],
  ["trefiori","Luca","Terenzi","C",18,22],
  ["trefiori","Nicol\u00f2","Sancisi","C",17,23],
  ["trefiori","Federico","Ciccione","C",16,25],
  ["trefiori","Tommaso","Bernardi","A",39,25],
  ["trefiori","Matteo","Prandelli","A",35,37],
  ["trefiori","Mohamed Ben","Kacem","A",35,32],
  ["trefiori","Joas van","Nek","A",14,22],
  ["trepenne","Mattia","Migani","P",22,34],
  ["trepenne","Devin","Benvenuti","P",15,18],
  ["trepenne","Federico","Andreani","P",10,32],
  ["trepenne","Domenico","Scarcella","D",23,21],
  ["trepenne","Manuel","Ferrani","D",18,39],
  ["trepenne","Gino","Meriano","D",14,20],
  ["trepenne","Redis","Kadiu","D",11,19],
  ["trepenne","Brian Joel","Ruiz","D",7,24],
  ["trepenne","Fabio","Sottile","D",5,33],
  ["trepenne","Katriel","Islamaj","C",29,27],
  ["trepenne","Patrick","Casadio","C",28,23],
  ["trepenne","Tommaso","Bartoli","C",28,22],
  ["trepenne","Lorenzo","Pastorelli","C",27,25],
  ["trepenne","Luca","Ceccaroli","C",23,31],
  ["trepenne","Lucio","Peluso","C",20,35],
  ["trepenne","Simone","Loiodice","C",19,37],
  ["trepenne","Maurice","Kamouni","C",18,22],
  ["trepenne","Tommaso","Bastianelli","C",18,23],
  ["trepenne","Valentino","Cenni","C",13,19],
  ["trepenne","Mattia","Cenni","C",11,20],
  ["trepenne","Mario","Cordioli","C",8,24],
  ["trepenne","Nicol\u00f2","Alfano","C",7,28],
  ["trepenne","Giacomo","Zafferani","C",5,30],
  ["trepenne","Riccardo","Pieri","A",36,31],
  ["trepenne","Danilo","Rinaldi","A",24,40],
  ["trepenne","Alexander","Carrer","A",10,25],
  ["trepenne","Abdel","Mansour","A",6,null],
  ["virtus","Giacomo","Venturini","P",22,22],
  ["virtus","Samuele","Guddo","P",20,27],
  ["virtus","Alberto","Sebastiani","P",7,41],
  ["virtus","Nicola","Gori","D",22,29],
  ["virtus","Umberto De","Lucia","D",19,34],
  ["virtus","Daniel","Piscaglia","D",15,33],
  ["virtus","Leonardo","Nunzella","D",15,34],
  ["virtus","Alex","Colombini","D",11,18],
  ["virtus","Diego","Madonna","D",9,21],
  ["virtus","Ilyas","Lahrach","D",8,23],
  ["virtus","Elia","Ciacci","C",29,24],
  ["virtus","Armando","Amati","C",28,31],
  ["virtus","Alessandro","Golinucci","C",27,31],
  ["virtus","Giammario","Piscitella","C",23,33],
  ["virtus","Ivan","Buonocunto","C",22,40],
  ["virtus","Arda Kaan","Yazici","C",19,20],
  ["virtus","Jacopo","Muggeo","C",15,36],
  ["virtus","Bryan","Blanco","C",10,21],
  ["virtus","Kevin","Lisanti","C",10,21],
  ["virtus","Nicol\u00f2","Borioni","C",8,24],
  ["virtus","Imre","Badalassi","A",38,31],
  ["virtus","Simone","Benincasa","A",38,25],
  ["virtus","Andrea","Gjoni","A",31,20],
  ["virtus","Marco","Gasperoni","A",26,22],
];
